CREATE TABLE IF NOT EXISTS `mydb`.`GRAU_DOCENTE` (
  `TP_ESCOLARIDADE` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TP_ESCOLARIDADE`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `mydb`.`CATEGORIA_IES` (
  `idCATEGORIA_IES` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCATEGORIA_IES`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `mydb`.`NIVEL_CURSOS` (
  `TP_GRAU_ACADEMICO` INT NOT NULL,
  `DescricaoGrau` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TP_GRAU_ACADEMICO`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `mydb`.`MODALIDADE_CURSO` (
  `idMODALIDADE_CURSO` INT NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMODALIDADE_CURSO`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `mydb`.`REGIAO` (
  `idREGIAO` INT NOT NULL,
  `NO_REGIAO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idREGIAO`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `mydb`.`ESTADO` (
  `idESTADO` INT NOT NULL,
  `idREGIAO_fk` INT NOT NULL,
  `NO_ESTADO` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idESTADO`),
  INDEX `idREGIAO_fk_idx` (`idREGIAO_fk` ASC) VISIBLE,
  CONSTRAINT `idREGIAO_fk`
    FOREIGN KEY (`idREGIAO_fk`)
    REFERENCES `mydb`.`REGIAO` (`idREGIAO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `mydb`.`CIDADE` (
  `CO_MUNICIPIO` INT NOT NULL,
  `idESTADO_fk` INT NOT NULL,
  `EH_CAPITAL` INT NOT NULL,
  `NO_MUNICIPIO` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`CO_MUNICIPIO`, `idESTADO_fk`),
  INDEX `idESTADO_fk_idx` (`idESTADO_fk` ASC) VISIBLE,
  CONSTRAINT `idESTADO_fk`
    FOREIGN KEY (`idESTADO_fk`)
    REFERENCES `mydb`.`ESTADO` (`idESTADO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `mydb`.`IES` (
  `ANO_CENSO` INT NOT NULL,
  `idIES` INT NOT NULL,
  `idCATEGORIA_fk` INT NOT NULL,
  `TP_ORGANIZACAO_ACADEMICA` INT NOT NULL,
  `CO_MUNICIPIO_fk` INT NOT NULL,
  `NO_IES` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`ANO_CENSO`, `idIES`, `idCATEGORIA_fk`, `TP_ORGANIZACAO_ACADEMICA`, `CO_MUNICIPIO_fk`),
  INDEX `idCATEGORIA_fk_idx` (`idCATEGORIA_fk` ASC) INVISIBLE,
  INDEX `CO_MUNICIPIO_fk_idx` (`CO_MUNICIPIO_fk` ASC) VISIBLE,
  INDEX `idIES_fk_idx` (`idIES` ASC) INVISIBLE,
  CONSTRAINT `idCATEGORIA_fk`
    FOREIGN KEY (`idCATEGORIA_fk`)
    REFERENCES `mydb`.`CATEGORIA_IES` (`idCATEGORIA_IES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CO_MUNICIPIO_fk`
    FOREIGN KEY (`CO_MUNICIPIO_fk`)
    REFERENCES `mydb`.`CIDADE` (`CO_MUNICIPIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `mydb`.`DOCENTE` (
  `ANO_CENSO` INT NOT NULL,
  `CO_DOCENTE_IES` VARCHAR(45) NOT NULL,
  `CO_DOCENTE` VARCHAR(45) NOT NULL,
  `idIES_fk` INT NOT NULL,
  `TP_ESCOLARIDADE` INT NOT NULL,
  `TP_COR_RACA` INT NOT NULL,
  `TP_SEXO` INT NOT NULL,
  `TP_SITUACAO` INT NOT NULL,
  `TP_DEFICIENCIA` INT NOT NULL,
  PRIMARY KEY (`ANO_CENSO`, `CO_DOCENTE_IES`, `CO_DOCENTE`, `idIES_fk`, `TP_ESCOLARIDADE`),
  INDEX `idUNIVERSIDADE_fk_idx` (`idIES_fk` ASC) VISIBLE,
  INDEX `idGRAU_DOCENTE_fk_idx` (`TP_ESCOLARIDADE` ASC) VISIBLE,
  CONSTRAINT `idIES_fk`
    FOREIGN KEY (`idIES_fk`)
    REFERENCES `mydb`.`IES` (`idIES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idGRAU_DOCENTE_fk`
    FOREIGN KEY (`TP_ESCOLARIDADE`)
    REFERENCES `mydb`.`GRAU_DOCENTE` (`TP_ESCOLARIDADE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `mydb`.`CURSOS` (
  `ANO_CENSO` VARCHAR(45) NOT NULL,
  `CO_CURSO` INT NOT NULL,
  `idIES_fk` INT NOT NULL,
  `TP_GRAU_ACADEMICO` INT NOT NULL,
  `TP_MODALIDADE_ENSINO` INT NOT NULL,
  `CO_MUNICIPIO_fk` INT NOT NULL,
  `NO_CURSO` VARCHAR(200) NOT NULL,
  `TP_SITUACAO` INT NOT NULL,
  `IN_AJUDA_DEFICIENTE` INT NOT NULL,
  `QT_MATRICULA_TOTAL` INT NOT NULL,
  `QT_CONCLUINTE_TOTAL` INT NOT NULL,
  `QT_INGRESSO_TOTAL` INT NOT NULL,
  PRIMARY KEY (`ANO_CENSO`, `CO_CURSO`, `idIES_fk`, `TP_GRAU_ACADEMICO`, `TP_MODALIDADE_ENSINO`, `CO_MUNICIPIO_fk`),
  INDEX `idIES_fk_idx` (`idIES_fk` ASC) INVISIBLE,
  INDEX `idGRAU_fk_idx` (`TP_GRAU_ACADEMICO` ASC) VISIBLE,
  INDEX `idMODALIDADE_CURSO_fk_idx` (`TP_MODALIDADE_ENSINO` ASC) VISIBLE,
  INDEX `CO_CURSO_fk_` (`CO_CURSO` ASC) VISIBLE,
  INDEX `CO_MUNICIPIO_fk_CURSOS_idx` (`CO_MUNICIPIO_fk` ASC) VISIBLE,
  CONSTRAINT `idIES_fk_`
    FOREIGN KEY (`idIES_fk`)
    REFERENCES `mydb`.`IES` (`idIES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TP_GRAU_ACADEMICO_fk`
    FOREIGN KEY (`TP_GRAU_ACADEMICO`)
    REFERENCES `mydb`.`NIVEL_CURSOS` (`TP_GRAU_ACADEMICO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TP_MODALIDADE_ENSINO_fk`
    FOREIGN KEY (`TP_MODALIDADE_ENSINO`)
    REFERENCES `mydb`.`MODALIDADE_CURSO` (`idMODALIDADE_CURSO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CO_MUNICIPIO_fk_CURSOS`
    FOREIGN KEY (`CO_MUNICIPIO_fk`)
    REFERENCES `mydb`.`CIDADE` (`CO_MUNICIPIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `mydb`.`ALUNO` (
  `ANO_CENSO` INT NOT NULL,
  `CO_ALUNO` BIGINT NOT NULL,
  `CO_ALUNO_CURSO` INT NOT NULL,
  `CO_CURSO_fk` INT NOT NULL,
  `idIES_fk` INT NOT NULL,
  `DATA_INGRESSO` DATETIME NOT NULL,
  `idSITUACAO_ALUNO_fk` INT NOT NULL,
  `IN_RESERVA_ENSINO_PUBLICO` INT NOT NULL,
  `IN_RESERVA_RENDA_FAMILIAR` INT NOT NULL,
  `IN_RESERVA_DEFICIENCIA` INT NOT NULL,
  `IN_RESERVA_ETNICO` INT NOT NULL,
  `IN_INGRESSO_VESTIBULAR` INT NOT NULL,
  `IN_INGRESSO_ENEM` INT NOT NULL,
  `TP_COR_RACA` INT NOT NULL,
  `TP_SEXO` INT NOT NULL,
  `IN_MATRICULA` INT NOT NULL,
  `IN_CONCLUINTE` INT NOT NULL,
  `IN_INGRESSO_TOTAL` INT NOT NULL,
  `TURNO_ALUNO` INT NOT NULL,
  PRIMARY KEY (`ANO_CENSO`, `CO_CURSO_fk`, `idIES_fk`, `DATA_INGRESSO`, `CO_ALUNO_CURSO`, `CO_ALUNO`),
  INDEX `idIES_fk__idx` (`idIES_fk` ASC) VISIBLE,
  INDEX `CO_CURSO_fk__idx` (`CO_CURSO_fk` ASC) VISIBLE,
  INDEX `CO_ALUNO_CURSO_fk` (`CO_ALUNO_CURSO` ASC) VISIBLE,
  CONSTRAINT `idIES_fk_ALUNO`
    FOREIGN KEY (`idIES_fk`)
    REFERENCES `mydb`.`IES` (`idIES`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CO_CURSO_fk_`
    FOREIGN KEY (`CO_CURSO_fk`)
    REFERENCES `mydb`.`CURSOS` (`CO_CURSO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;